# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rRjOsQfkt7ju21CdKRiKGIJK77g34DeS
"""

# metrics.py
from PIL import Image
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt

def calculate_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred)
    return accuracy, cm

def plot_example(correct_example, incorrect_example):
    correct_example = Image.open("confusion_matrix.png")
    incorrect_example = Image.open("confusion_matrix_incorrect.png")
    pass