# -*- coding: utf-8 -*-
"""random_forest_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a37l1FWxUaoA82bIztj4DemBOn7wCbb
"""

# random_forest_model.py

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

def predict_subscription_status(input_data):
    # Загрузим модель
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    
    # Загрузим данные
    data = pd.read_csv('bank.csv', sep=';')
    X = data.drop('y', axis=1)
    y = data['y']
    X = pd.get_dummies(X, drop_first=True)

    # Обучим модель
    model.fit(X, y)

    # Предскажем результаты
    y_pred = model.predict(input_data)

    return y_pred

