# -*- coding: utf-8 -*-
"""random_forest_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a37l1FWxUaoA82bIztj4DemBOn7wCbb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv('bank.csv', sep = ';')
data

# Подготовим данные
X = data.drop('y', axis=1)
y = data['y']
X = pd.get_dummies(X, drop_first=True)

# Разделим данные на тренировочную и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Обучим модель
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Предскажем результаты
y_pred = model.predict(X_test)

# Посчитаем точность модели
accuracy = accuracy_score(y_test, y_pred)

# Выведем точность
print(f"Точность модели: {accuracy}")

