# -*- coding: utf-8 -*-
"""report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVk5dM-vicSc75FPYHm59dUGEU1GMJ_B
"""

# report.py

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, recall_score
from random_forest_model import predict_subscription_status

def generate_report():
    # Загрузим данные
    data = pd.read_csv('bank.csv', sep=';')
    X = data.drop('y', axis=1)
    y = data['y']
    X = pd.get_dummies(X, drop_first=True)

    # Получим предсказания модели
    y_pred = predict_subscription_status(X)

    # Посчитаем метрики
    accuracy = accuracy_score(y, y_pred)
    recall = recall_score(y, y_pred, pos_label='yes')  # Указываем 'yes' как положительную метку

    # Сохраним метрики в файл
    with open('metrics.txt', 'w') as file:
        file.write(f'Accuracy: {accuracy}\n')
        file.write(f'Recall: {recall}\n')

    # Создадим график
    plt.figure(figsize=(10, 6))
    plt.scatter(range(len(y)), y, label='True Labels', color='blue')
    plt.scatter(range(len(y)), y_pred, label='Predicted Labels', color='red', alpha=0.5)
    plt.xlabel('Sample Index')
    plt.ylabel('Label')
    plt.legend()
    plt.savefig('plot.png')

if __name__ == '__main__':
    generate_report()



